title: "Erfan Doroudian"
description: "AI Researcher | RL, Autonomous Driving, Vision-Language Models"
baseurl: ""
url: "https://yourusername.github.io"

# Navigation
header_pages:
  - index.md
  - projects.md
  - publications.md
  - about.md
